name: Basic

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build-linux-x64-android-hl2dm:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build android-armabi-v7a-hl2dm
      run: |
        scripts/build-ubuntu-i386.sh
        ls -la
        find ./build -type f -name "*.o" -delete
        find ./build -type d -empty -delete
        rm -rf android*.zip
        zip -r build-android-hl2dm-armv7a.zip build
    - uses: actions/upload-artifact@v3
      with:
        name: Source Engine-hl2dm-Android
        path: ./*.zip

  build-linux-Android-error:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build linux-amd64
      run: |
        scripts/build-ubuntu-amd64.sh
        ls -la
        find ./build -type f -name "*.o" -delete
        find ./build -type d -empty -delete
        rm -rf android*.zip
        zip -r build-hl2-32.zip build
    - uses: actions/upload-artifact@v3
      with:
        name: Source Engine-hl2-32-bit
        path: ./*.zip

  build-android-armv7a-css:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build android-armv7a-css
      run: |
        scripts/build-android-armv7a.sh
        ls -la
        find ./build -type f -name "*.o" -delete
        find ./build -type d -empty -delete
        rm -rf android*.zip
        zip -r build-android-css-armv7a.zip build
    - uses: actions/upload-artifact@v3
      with:
        name: Source Engine -css-Android armv7a
        path: ./*.zip

  build-windows-i386:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - name: Build windows-i386
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T debug --build-games=cstrike
        ./waf.bat build
        md .\build1
        md .\build1\bin
        md .\build1\game
        md .\build1\game\bin
        Get-ChildItem -Recurse -Filter "*.dll" | Move-Item -Force -Verbose -Destination .\build1\bin
        Get-ChildItem -Recurse -Filter "client.dll" | Move-Item -Force -Verbose -Destination .\build1\game\bin
        Get-ChildItem -Recurse -Filter "server.dll" | Move-Item -Force -Verbose -Destination .\build1\game\bin
        Get-ChildItem -Recurse -Filter "*launcher.exe" | Move-Item -Force -Verbose -Destination .\build1
        Remove-item .\build -Recurse -Force
        ren .\build1 .\build
        robocopy ".\build" ".\build" /S /move
        zip -r build-windows-i386.zip build
    - uses: actions/upload-artifact@v3
      with:
        name: Source Engine - Windows 32-bit
        path: ./*.zip
