name: Basic

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build-linux-x64-android-hl2dm:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build android-armabi-v7a-hl2dm
      run: |
        scripts/build-ubuntu-i386.sh
        ls -la
        find ./build -type f -name "*.o" -delete
        find ./build -type d -empty -delete
        rm -rf android*.zip
        zip -r build-android-hl2dm-armv7a.zip build
    - uses: actions/upload-artifact@v3
      with:
        name: Source Engine-hl2dm-Android
        path: ./*.zip

  build-linux-amd64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build linux-amd64
      run: |
        scripts/build-ubuntu-amd64.sh
        ls -la
        find ./build -type f -name "*.o" -delete
        find ./build -type f -name "*.pdb" -delete
        find ./build -type d -empty -delete
        zip -r build-linux-amd64.zip build
    - uses: actions/upload-artifact@v3
      with:
        name: Source Engine - Linux 64-bit
        path: ./*.zip

  build-android-armv7a-css:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build android-armv7a-css
      run: |
        scripts/build-android-armv7a.sh
        ls -la
        find ./build -type f -name "*.o" -delete
        find ./build -type d -empty -delete
        rm -rf android*.zip
        zip -r build-android-css-armv7a.zip build
    - uses: actions/upload-artifact@v3
      with:
        name: Source Engine -css-Android armv7a
        path: ./*.zip

  build-windows-i386:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - name: Build windows-i386
      run: |
        git submodule init && git submodule update
        # ./waf.bat configure -T release
        # ./waf.bat build
        ./waf.bat configure -T debug
        ./waf.bat build
        Remove-Item -Path .\build\* -Include *.o -Recurse -Force
        Remove-Item -Path .\build\* -Include *.pdb -Recurse -Force
        robocopy ".\build" ".\build" /S /move
        choco install zip
        zip -r build-windows-i386.zip build
    - uses: actions/upload-artifact@v3
      with:
        name: Source Engine - Windows 32-bit
        path: ./*.zip
