name: Build upload test

on:
push:
branches:
- "*"
pull_request:
branches:
- "*"

build-android-armv7a:
runs-on: ubuntu-18.04

steps:
- uses: actions/checkout@v2
- name: Build android-armv7a
run: |
scripts/build-android-armv7a.sh

- name: Upload Release
uses: actions/upload-artifact@v2
with:
name: build.tar.gz
path: .
