name: Tests-aarch64&x86

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  tests-linux-x86:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    - name: Run tests-x86_ver-android
      run: |
        git submodule init && git submodule update
        wget https://dl.google.com/android/repository/android-ndk-r10e-linux-x86_64.zip -o /dev/null
        unzip android-ndk-r10e-linux-x86_64.zip
        export ANDROID_NDK_HOME=$PWD/android-ndk-r10e/
        export NDK_HOME=$PWD/android-ndk-r10e/
        ./waf --help
        #./waf configure -T release --android=x86,host,21 --togl --build-games=hl2 --use-ccache --64bits --disable-warns
        ./waf build
        ./waf configure -T release --android=armeabi-v7a-hard,4.9,21 --togl --build-game=hl2 --disable-warns &&
        ./waf --help
        ls -la
        find ./build -type f -name "*.o" -delete
        find ./build -type d -empty -delete
        rm -rf android*.zip
        zip -r build-android-hl2-x86_togl.zip build
    - uses: actions/upload-artifact@v3
      with:
        name: Source Engine-hl2-32bit-x86
        path: ./*.zip
