name: Tests

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  tests-linux-i386:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests-dod-android
      run: |
        scripts/tests-ubuntu-i386.sh
        ls -la
        find ./build -type f -name "*.o" -delete
        find ./build -type d -empty -delete
        rm -rf android*.zip
        zip -r build-android-hls-armv7a.zip build
    - uses: actions/upload-artifact@v3
      with:
        name: Source Engine-hls-32-bit
        path: ./*.zip

  tests-linux-amd64:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    - name: Run tests linux-dod
      run: |
        scripts/tests-ubuntu-amd64.sh
        ls -la
        find ./build -type f -name "*.o" -delete
        find ./build -type d -empty -delete
        rm -rf android*.zip
        zip -r build-android-dod-armv7a.zip build
    - uses: actions/upload-artifact@v3
      with:
        name: Source Engine-dods-32-bit
        path: ./*.zip

  
